### ISSUE TITLE
Not able to run the examples on TPU colab pro

### ISSUE THREAD

**Issue by Mistobaan** [LargeWorldModel/LWM#8]
see this colab: https://gist.github.com/Mistobaan/605e212f951c5ae82ea420765fce381b

What am I doing wrong?  the scripts might require better naming to match the released model weights.

Thank you again for this work !

**Comment by unrelatedlabs** [comment]
try removing the mesh_dim argument or setting it to the default from the code 

That was required to get it working on my mac

**Comment by Mistobaan** [comment]
Can you share the exact command line you used on the mac?

**Comment by Mistobaan** [comment]
managed to run it without the mesh_dim. updated colab

**Comment by FinaritrAndrianiaina** [comment]
Hi. I tried your colab and I just get ^C and no output image. I can't find what the problem is :/
env: PYTHONPHAT=/content/LWM/
env: NUMEXPR_MAX_THREADS=12
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
0it [00:00, ?it/s]
I0219 10:25:56.072886 139828185026560 xla_bridge.py:660] Unable to initialize backend 'cuda': FAILED_PRECONDITION: No visible GPU devices.
I0219 10:25:56.073255 139828185026560 xla_bridge.py:660] Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: CUDA
I0219 10:25:56.074381 139828185026560 xla_bridge.py:660] Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
^C

**Comment by jayavanth** [comment]
> Hi. I tried your colab and I just get ^C and no output image. I can't find what the problem is :/ env: PYTHONPHAT=/content/LWM/ env: NUMEXPR_MAX_THREADS=12 The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`. 0it [00:00, ?it/s] I0219 10:25:56.072886 139828185026560 xla_bridge.py:660] Unable to initialize backend 'cuda': FAILED_PRECONDITION: No visible GPU devices. I0219 10:25:56.073255 139828185026560 xla_bridge.py:660] Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: CUDA I0219 10:25:56.074381 139828185026560 xla_bridge.py:660] Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory ^C

Not enough resources. Most probably GPU RAM. The program is getting killed (see the `^C` at the end of your output)

**Comment by FinaritrAndrianiaina** [comment]
Thanks 👍🏼

**Comment by s-suryakiran** [comment]
Hey, I tried running this notebook using Colab free account on TPU, but I am getting the following output, Any help would be greatly appreciated:

env: PYTHONPHAT=/content/LWM/
env: NUMEXPR_MAX_THREADS=12
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
0it [00:00, ?it/s]
I0324 00:46:41.363700 138855881940992 xla_bridge.py:633] Unable to initialize backend 'cuda': FAILED_PRECONDITION: No visible GPU devices.
I0324 00:46:41.364099 138855881940992 xla_bridge.py:633] Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: CUDA
I0324 00:46:41.365276 138855881940992 xla_bridge.py:633] Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
